# Generated by Django 6.1 on 2026-08-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('total_books', models.PositiveIntegerField(default=0)),
                ('available_books', models.PositiveIntegerField(default=0)),
                ('issued_to_teachers', models.PositiveIntegerField(default=0)),
                ('issued_to_students', models.PositiveIntegerField(default=0)),
                ('returned_books', models.PositiveIntegerField(default=0)),
                ('lost_books', models.PositiveIntegerField(default=0)),
                ('damaged_books', models.PositiveIntegerField(default=0)),
                ('written_off_books', models.PositiveIntegerField(default=0)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='geography.district')),
                ('jamoat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='geography.jamoat')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='geography.region')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='schools.school')),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
