# Generated by Django 6.1 on 2026-08-27 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(blank=True, max_length=300)),
                ('to_location', models.CharField(blank=True, max_length=300)),
                ('transaction_type', models.CharField(choices=[('WAREHOUSE_TO_SCHOOL', 'Warehouse to School'), ('LIBRARIAN_TO_TEACHER', 'Librarian to Teacher'), ('TEACHER_TO_STUDENT', 'Teacher to Student'), ('STUDENT_RETURN', 'Student Return'), ('TEACHER_RETURN', 'Teacher Return'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('WRITTEN_OFF', 'Written Off')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='library.bookcopy')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Transaction',
                'verbose_name_plural': 'Book Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
